#nullable enable
using System.Collections.Generic;

namespace Alundra.Scripts;

/// <summary>
/// Verbatim port of the opcode size/name table from
/// AlundraEngine.Gameplay.Scripts.EventCodeDebugger.CommandPropertiesByCode (alundra-datas-analyser
/// AlundraTools/AlundraEngine/Gameplay/Scripts/EventCodeDebugger.cs:126-326) - the complete map from
/// opcode byte to instruction size in bytes (opcode + parameters) and the original's own short
/// description, covering every one of the 197 named opcodes (0x00-0xC4, 0xFF). Names are kept for log
/// messages only; only <see cref="Sizes"/> drives interpreter behaviour (see
/// <see cref="AlundraEventProgramRunner"/>'s unknown-opcode policy).
///
/// A handful of entries carry size 0 in the source table itself (0x0E/0x0F/0x13/0x14/0x18 "do nothing
/// (debug command)", 0x76/0x77/0x9D/0xAE "not implemented"/"fatal error") - the original's own
/// GetCommandsOnlyAtOffset/GetCommands decoders treat size &lt; 1 the same way this port's
/// unknown-opcode fallback does (cannot safely advance), so they are intentionally NOT special-cased
/// here; they fall through the same "unknown size -&gt; terminate" path as a truly unlisted byte.
/// </summary>
public static class EventOpcodeSizeTable
{
    public sealed record Entry(int Size, string Name);

    public static readonly IReadOnlyDictionary<byte, Entry> Entries = new Dictionary<byte, Entry>
    {
        { 0x00, new(1, "Break") },
        { 0x01, new(1, "Do nothing (debug command)") },
        { 0x02, new(3, "Goto") },
        { 0x03, new(3, "If true goto") },
        { 0x04, new(3, "If false goto") },
        { 0x05, new(3, "Flag on") },
        { 0x06, new(3, "Flag off") },
        { 0x07, new(8, "Check entity in area") },
        { 0x08, new(2, "Turn") },
        { 0x09, new(2, "Set direction") },
        { 0x0A, new(1, "Reverse direction") },
        { 0x0B, new(4, "Wait until entity moves beyond radius") },
        { 0x0C, new(1, "Set random dir") },
        { 0x0D, new(3, "Dialog") },
        { 0x0E, new(0, "Do nothing (debug command)") },
        { 0x0F, new(0, "Do nothing (debug command)") },
        { 0x10, new(1, "Player lose control") },
        { 0x11, new(1, "Player gain control") },
        { 0x12, new(2, "Play sound 1") },
        { 0x13, new(0, "Do nothing (debug command)") },
        { 0x14, new(0, "Do nothing (debug command)") },
        { 0x15, new(1, "Reset z pos") },
        { 0x16, new(1, "High gravity") },
        { 0x17, new(1, "Low gravity") },
        { 0x18, new(0, "Do nothing") },
        { 0x19, new(1, "Deactivate entity") },
        { 0x1A, new(2, "Set anim") },
        { 0x1B, new(3, "Fly") },
        { 0x1C, new(2, "Repeat anim") },
        { 0x1D, new(2, "Repeat anim with collision") },
        { 0x1E, new(3, "Walk") },
        { 0x1F, new(3, "Walk with collision") },
        { 0x20, new(3, "Check Z distance and collided Z") },
        { 0x21, new(3, "Is within Z distance") },
        { 0x22, new(1, "Clamp forceZ to height target") },
        { 0x23, new(1, "Clamp forceZ and no collided Z") },
        { 0x24, new(1, "Wait force adjusted") },
        { 0x25, new(1, "Wait entity collision z or 144") },
        { 0x26, new(1, "Wait force adjusted or entity collision z") },
        { 0x27, new(1, "Face player") },
        { 0x28, new(1, "Set EntityFlags.ClassB") },
        { 0x29, new(1, "Clear EntityFlags.ClassB") },
        { 0x2A, new(1, "Set EntityFlags.ClassA") },
        { 0x2B, new(1, "Clear EntityFlags.ClassA") },
        { 0x2C, new(2, "Check no entity by function id") },
        { 0x2D, new(2, "Activate entity") },
        { 0x2E, new(2, "Destroy entity") },
        // D-E7-7 (docs/plan-e7-mutation-tuiles.md, slice E7.c): relabeled from "Check moving in dir" - a
        // contresens describing the SCRIPT'S intention (the four real map-389 occurrences all test bit
        // 0x1000 = Up, "the player pushes toward the hatch"), not Script_47_02F's own semantics, which is
        // a raw pad-button test (see AlundraEventProgramRunner.Dispatch case 0x2F's own doc).
        { 0x2F, new(4, "Check pad buttons") },
        { 0x30, new(5, "If flag on") },
        { 0x31, new(5, "If flag off") },
        { 0x32, new(3, "Toggle flag") },
        { 0x33, new(9, "Check flags on") },
        { 0x34, new(9, "Check flags off") },
        { 0x35, new(3, "Wait flag on") },
        { 0x36, new(3, "Wait flag off") },
        { 0x37, new(2, "Wait") },
        { 0x38, new(5, "Set MapIdToInternalMapIndex") },
        { 0x39, new(1, "Wait for dialog") },
        { 0x3A, new(2, "Set TargetDirection") },
        { 0x3B, new(7, "Check player in area") },
        { 0x3C, new(7, "If entity in zone with flag 0x80") },
        { 0x3D, new(7, "If entity in zone") },
        { 0x3E, new(1, "Is player riding entity") },
        { 0x3F, new(1, "If entity riding me") },
        { 0x40, new(3, "Set program index") },
        { 0x41, new(3, "Set sprite program index") },
        { 0x42, new(1, "SetLogicContextEntity = PlayerEntity") },
        { 0x43, new(2, "Set LogicContextEntity") },
        { 0x44, new(1, "Wait dialog choice") },
        { 0x45, new(1, "Clear EntityFlags.NoObstacleSlide") },
        { 0x46, new(1, "Set EntityFlags.NoObstacleSlide") },
        { 0x47, new(1, "If collided Z or ForceAdjusted") },
        { 0x48, new(1, "If collided Z or hit") },
        { 0x49, new(1, "Restart") },
        { 0x4A, new(1, "If true restart") },
        { 0x4B, new(1, "If false restart") },
        { 0x4C, new(2, "Set text flags") },
        { 0x4D, new(1, "Try to activate textAutoAdvanceFlag") },
        { 0x4E, new(2, "Set debug flag") },
        { 0x4F, new(1, "Activate debug text auto advance") },
        { 0x50, new(2, "Set dialog choice") },
        { 0x51, new(1, "Get dialog choice") },
        { 0x52, new(1, "Use portal") },
        { 0x53, new(8, "Change map") },
        { 0x54, new(5, "Set walkable") },
        { 0x55, new(5, "Set unwalkable") },
        { 0x56, new(2, "Change area tiles") },
        { 0x57, new(9, "Goto by animation direction") },
        { 0x58, new(9, "Directional branch") },
        { 0x59, new(3, "Set entity anim") },
        { 0x5A, new(3, "Turn entity") },
        { 0x5B, new(4, "Turn entity with anim") },
        { 0x5C, new(4, "Dialog with entity") },
        { 0x5D, new(2, "Set entity Status = 3") },
        { 0x5E, new(4, "Set forceZ for entities") },
        { 0x5F, new(1, "Wait for anim or distance") },
        { 0x60, new(2, "Is riding entity") },
        { 0x61, new(2, "Is riding entity 2") },
        { 0x62, new(4, "Set entities flags (low 16 bits)") },
        { 0x63, new(4, "Clear entities flags (low 16 bits)") },
        { 0x64, new(8, "Set entities position") },
        { 0x65, new(8, "Move entity position") },
        { 0x66, new(3, "Copy context and assign script") },
        { 0x67, new(2, "Camera follow entity") },
        { 0x68, new(1, "Camera stop follow entity") },
        { 0x69, new(7, "Camera look at") },
        { 0x6A, new(1, "Save entity position") },
        { 0x6B, new(3, "If entity x < threshold") },
        { 0x6C, new(3, "If entity y < threshold") },
        { 0x6D, new(3, "If entity z < threshold") },
        { 0x6E, new(1, "Is force adjusted") },
        { 0x6F, new(1, "Is collided with entity Z") },
        { 0x70, new(1, "Is above ground") },
        { 0x71, new(1, "Get hit counter") },
        { 0x72, new(1, "Set LastTargetAnim and Direction") },
        { 0x73, new(2, "Initialize timer _30") },
        { 0x74, new(3, "Update timer _30") },
        { 0x75, new(2, "Play sound effect") },
        { 0x76, new(0, "not implemented") },
        { 0x77, new(0, "not implemented") },
        { 0x78, new(4, "Store choice param and jump") },
        { 0x79, new(3, "Jump if choice accepted") },
        { 0x7A, new(3, "Jump if choice rejected") },
        { 0x7B, new(5, "Jump if flag set store param") },
        { 0x7C, new(5, "Jump if flag clear store param") },
        { 0x7D, new(1, "Jump relative from stored param") },
        { 0x7E, new(1, "Conditional jump if true") },
        { 0x7F, new(1, "Conditional jump if false") },
        { 0x80, new(3, "Jump from param if flag set") },
        { 0x81, new(3, "Jump from param if flag clear") },
        { 0x82, new(2, "Handle map trigger") },
        { 0x83, new(3, "If number of item > 0") },
        { 0x84, new(2, "Use item") },
        { 0x85, new(7, "Set map tiles") },
        { 0x86, new(4, "Add DamagedTickCounter") },
        { 0x87, new(3, "If TouchingEntity anim value") },
        { 0x88, new(3, "") },
        { 0x89, new(9, "Set matched entities position relative to reference") },
        { 0x8A, new(8, "Spawn entity at position") },
        { 0x8B, new(9, "Spawn entity next to entity") },
        { 0x8C, new(2, "Random < variable") },
        { 0x8D, new(2, "Check PosZ <= TerrainHeight + 1") },
        { 0x8E, new(5, "Set scrolling parameters") },
        { 0x8F, new(1, "Set scrolling flag = 0") },
        { 0x90, new(2, "Create effect") },
        { 0x91, new(2, "Disable effect") },
        { 0x92, new(3, "Set effect anim") },
        { 0x93, new(8, "Set effect pos") },
        { 0x94, new(8, "Set effect forces") },
        { 0x95, new(10, "Check entities attacking hitbox") },
        { 0x96, new(3, "Restore HP") },
        { 0x97, new(2, "Spend money") },
        { 0x98, new(3, "Add money") },
        { 0x99, new(3, "Try spend money") },
        { 0x9A, new(3, "Enough money?") },
        { 0x9B, new(1, "Set warp disabled = 1") },
        { 0x9C, new(1, "Set warp disabled = 0") },
        { 0x9D, new(0, "Fatal Error - Exit") },
        { 0x9E, new(6, "Count walkable tile") },
        { 0x9F, new(2, "Wait open chest") },
        { 0xA0, new(8, "Adjusted effect pos") },
        { 0xA1, new(9, "Set effect pos with entity") },
        { 0xA2, new(8, "Create effect with pos") },
        { 0xA3, new(9, "Create effect with entity pos") },
        { 0xA4, new(3, "Set scrolling mode") },
        { 0xA5, new(1, "Stop all sound") },
        { 0xA6, new(2, "Load bgm") },
        { 0xA7, new(3, "Play music") },
        { 0xA8, new(1, "Is sound loading") },
        { 0xA9, new(2, "") },
        { 0xAA, new(2, "") },
        { 0xAB, new(4, "Play sound with tone/volume/mix") },
        { 0xAC, new(4, "Set entity shadow size") },
        { 0xAD, new(9, "Check entity in AABB") },
        { 0xAE, new(0, "Fatal Error - Exit") },
        { 0xAF, new(7, "Set fade transition with color") },
        { 0xB0, new(5, "Set warp fade color and duration") },
        { 0xB1, new(1, "Check fade and warp flags") },
        { 0xB2, new(3, "Compare entity groups") },
        { 0xB3, new(9, "Set pad buttons") },
        { 0xB4, new(2, "Check ForceZ < 0") },
        { 0xB5, new(2, "Check ForceZ >= 0") },
        { 0xB6, new(2, "Check ForceZ != 0") },
        { 0xB7, new(3, "Check TargetAnimation") },
        { 0xB8, new(3, "Check TargetDirection") },
        { 0xB9, new(2, "Start CD streaming") },
        { 0xBA, new(1, "Check if loading from CD") },
        { 0xBB, new(1, "Check retry or title screen") },
        { 0xBC, new(2, "Increase player HPMax") },
        { 0xBD, new(3, "Play sound 2") },
        { 0xBE, new(3, "Play sound 2 (bis)") },
        { 0xBF, new(5, "Play sound with tone/volume/mix") },
        { 0xC0, new(2, "Set equipped weapon") },
        { 0xC1, new(1, "Set player flag &= 0xffffff7f") },
        { 0xC2, new(2, "Check something save") },
        { 0xC3, new(1, "Restore and init HP and MP") },
        { 0xC4, new(6, "Dialog with entity and name") },
        { 0xFF, new(1, "End script") },
    };
}
