#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Alundra.Scripts;
using CasaEngine.Core.Logging;
using CasaEngine.Engine.Environment;
using CasaEngine.Framework.Dialogue.Assets;
using CasaEngine.Framework.Dialogue.Runtime;
using Xunit;

namespace Alundra.Tests;

/// <summary>
/// E19.f2b1b T1 (docs/plan-e19-opcodes.md, "E19.f2b1b - Etat dessine de la boite et oracle etendu"): the DRAWN state of the dialogue box - what the binary's
/// <c>MsgBoxRender</c> 0x80046EF0 puts in the ordering table at each pass - for the six scenarios of the annex (<c>docs/plan-e19-f2b1-annexe/values/S1.csv</c> to
/// <c>S6.csv</c>, generated by <c>scripts/scenarios.py</c> from <c>model_drawn.py</c>): the oracle (<see cref="AlundraTextBoxOracle"/>, extended, written from the model) equals
/// the tables in their own form, and the box (<see cref="AlundraDialogueBox"/>) equals them under one rule for the pass that ends a scroll. Pass 0 of a table is the pass of
/// the opening (no drawing); pass p is the p-th call of <see cref="AlundraDialogueDirector.Pass"/> after <see cref="AlundraDialogueDirector.Open"/>. The advances of the
/// glyphs come from the binary's own width table (the oracle's), injected into the director; the production reader of <c>UI/font3.fnt</c> is tested on the real export (S025
/// of map 472) and on a project without the file.
/// </summary>
public sealed class AlundraTextBoxDrawnStateTests : IDisposable
{
    private static readonly AlundraDialogueDirector Director = AlundraDialogueDirector.Instance;
    private const string Br = "[br trimwhitespace=false/]";

    private readonly string _previousProjectPath = EngineEnvironment.ProjectPath;

    public AlundraTextBoxDrawnStateTests()
    {
        Reset();
    }

    public void Dispose()
    {
        Reset();
        EngineEnvironment.ProjectPath = _previousProjectPath;
    }

    private static void Reset()
    {
        Director.ResetForTests();
        Director.AdvanceProviderForTests = null;
        AlundraDialogueCapturePresenter.ResetForTests();
        AlundraFont3Advances.ResetForTests();
    }

    // ---- the tables ---------------------------------------------------------------------------------------------------------

    private sealed record TableRow(int Pass, bool Drawn, string Kind, int FrameY, int CfgYBefore, int ClipX, int ClipTop, int ClipW, int ClipH, int Offset, bool Ending,
        (string Text, int X, int Y)[] Rows, int? CursorImage, int CursorU, int CursorX, int CursorY);

    private static string ValuesDirectory()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            var candidate = Path.Combine(directory.FullName, "docs", "plan-e19-f2b1-annexe", "values");
            if (File.Exists(Path.Combine(candidate, "S1.csv")))
            {
                return candidate;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("docs/plan-e19-f2b1-annexe/values not found above " + AppContext.BaseDirectory);
    }

    private static List<TableRow> LoadTable(string name)
    {
        var rows = new List<TableRow>();
        foreach (var line in File.ReadAllLines(Path.Combine(ValuesDirectory(), name + ".csv")).Skip(1))
        {
            var c = line.Split(';');
            Assert.Equal(25, c.Length);
            var pass = int.Parse(c[0]);
            if (c[2] == "0")
            {
                rows.Add(new TableRow(pass, false, string.Empty, 0, 0, 0, 0, 0, 0, 0, false, Array.Empty<(string, int, int)>(), null, 0, 0, 0));
                continue;
            }

            var cells = new (string Text, int X, int Y)[3];
            for (var r = 0; r < 3; r++)
            {
                cells[r] = (c[12 + 3 * r], int.Parse(c[13 + 3 * r]), int.Parse(c[14 + 3 * r]));
            }

            var hasCursor = c[21].Length > 0;
            rows.Add(new TableRow(
                pass, true, c[3], int.Parse(c[4]), int.Parse(c[5]), int.Parse(c[6]), int.Parse(c[7]), int.Parse(c[8]), int.Parse(c[9]), int.Parse(c[10]), c[11] == "1", cells,
                hasCursor ? int.Parse(c[21]) : null, hasCursor ? Convert.ToInt32(c[22], 16) : 0, hasCursor ? int.Parse(c[23]) : 0, hasCursor ? int.Parse(c[24]) : 0));
        }

        return rows;
    }

    // ---- the six scenarios ----------------------------------------------------------------------------------------------------

    private sealed record Scenario(string Name, string[] Pages, Func<int, (bool Held, bool Pressed)> Pad)
    {
        public DialogueAsset Asset() => DialogueTestAssets.BuildRaw("drawn-" + Name, "Start", Pages);
    }

    private static (bool, bool) NoButton(int pass) => (false, false);

    private static (bool, bool) EveryPass(int pass) => (true, true);

    private static (bool, bool) PressesAt60And120(int pass) => (pass is 60 or 120, pass is 60 or 120);

    private static Scenario Of(string name) => name switch
    {
        "S1" => new Scenario(name, new[] { "AB" }, NoButton),
        "S2" => new Scenario(name, new[] { $"Bonjour, Alundra !{Br}deuxième ligne" }, NoButton),
        "S3" => new Scenario(name, new[]
        {
            "[voice id=-1 trimwhitespace=false/][center trimwhitespace=false/]Roue de la fortune !" + Br
            + "[center trimwhitespace=false/]Florin[glyph id=21 trimwhitespace=false/]Roulette        [empty trimwhitespace=false/]",
        }, NoButton),
        "S4" => new Scenario(name, new[] { $"gypjq{Br}deux{Br}trois{Br}quatre" }, NoButton),
        "S5" => new Scenario(name, new[] { $"l1{Br}l2{Br}gypjq" }, EveryPass),
        "S6" => new Scenario(name, new[] { "a", "b", "c" }, PressesAt60And120),
        _ => throw new ArgumentException(name),
    };

    public static IEnumerable<object[]> ScenarioNames() => new[] { "S1", "S2", "S3", "S4", "S5", "S6" }.Select(n => new object[] { n });

    private static string Shown(string text) =>
        string.Concat(text.Select(c => (c >= 0x20 && c < 0x7F) || (c >= 0xA0 && c <= 0xFF) ? c.ToString() : $"<{(int)c}>"));

    // ---- the oracle against the tables ----------------------------------------------------------------------------------------

    [Theory]
    [MemberData(nameof(ScenarioNames))]
    public void TheOracle_DrawsWhatTheTableSays_AtEveryPass(string name)
    {
        var scenario = Of(name);
        var table = LoadTable(name);
        var oracle = new AlundraTextBoxOracle();
        var bytes = OraclePages.NodeBytes(scenario.Asset(), "Start", out _);

        oracle.Render(false, false); // pass 0 of a table: the box pass of the frame of the opening runs BEFORE the script that opens
        Assert.True(oracle.TryOpen(bytes, 1));
        Assert.Null(oracle.Drawn);
        Assert.Equal(0, table[0].Pass);
        Assert.False(table[0].Drawn);

        foreach (var t in table.Skip(1))
        {
            var (held, pressed) = scenario.Pad(t.Pass);
            oracle.Render(held, pressed);
            var where = $"{name} pass {t.Pass}";
            var d = oracle.Drawn;
            Assert.True(t.Drawn == (d is not null), $"{where}: drawn {d is not null}, table {t.Drawn}");
            if (d is null)
            {
                continue;
            }

            Assert.True(t.Kind == d.Kind, $"{where}: kind {d.Kind}, table {t.Kind}");
            Assert.True(t.FrameY == d.Y, $"{where}: frame Y {d.Y}, table {t.FrameY}");
            Assert.True(t.CfgYBefore == d.CfgYBefore, $"{where}: cfg Y before {d.CfgYBefore}, table {t.CfgYBefore}");
            Assert.True((t.ClipX, t.ClipTop, t.ClipW, t.ClipH) == (d.ClipX, d.ClipTop, d.ClipWidth, d.ClipHeight),
                $"{where}: clip ({d.ClipX}, {d.ClipTop}, {d.ClipWidth}, {d.ClipHeight}), table ({t.ClipX}, {t.ClipTop}, {t.ClipW}, {t.ClipH})");
            Assert.True(t.Offset == d.Offset, $"{where}: offset {d.Offset}, table {t.Offset}");
            Assert.True(t.Ending == d.Ending, $"{where}: ending {d.Ending}, table {t.Ending}");
            for (var r = 0; r < 3; r++)
            {
                var row = d.RowsVisible[r];
                Assert.True(
                    t.Rows[r] == (row.Text, row.X, row.Y),
                    $"{where}: row {r} ({row.Text}, {row.X}, {row.Y}), table ({t.Rows[r].Text}, {t.Rows[r].X}, {t.Rows[r].Y})");
            }

            Assert.True(t.CursorImage == d.Cursor?.Image, $"{where}: cursor image {d.Cursor?.Image}, table {t.CursorImage}");
            if (d.Cursor is { } cursor)
            {
                Assert.True((t.CursorU, t.CursorX, t.CursorY) == (cursor.U, cursor.X, cursor.Y),
                    $"{where}: cursor (u {cursor.U}, {cursor.X}, {cursor.Y}), table (u {t.CursorU}, {t.CursorX}, {t.CursorY})");
            }
        }
    }

    [Fact]
    public void TheOracle_OnThePassThatEndsAScroll_KeepsTheCpuListBesideTheVisibleOne()
    {
        var scenario = Of("S4");
        var oracle = new AlundraTextBoxOracle();
        oracle.Render(false, false);
        Assert.True(oracle.TryOpen(OraclePages.NodeBytes(scenario.Asset(), "Start", out _), 1));
        for (var pass = 1; pass <= 100; pass++)
        {
            oracle.Render(false, false);
        }

        var drawn = oracle.Drawn!;
        Assert.True(drawn.Ending);
        Assert.Equal(new[] { ("gypjq", 32, 157), ("deux", 32, 173), ("trois", 32, 189) }, drawn.RowsCpu.Select(r => (r.Text, r.X, r.Y)).ToArray());
        Assert.Equal(new[] { (string.Empty, 32, 157), ("deux", 32, 173), ("trois", 32, 189) }, drawn.RowsVisible.Select(r => (r.Text, r.X, r.Y)).ToArray());
        Assert.Equal(16, drawn.Offset);
    }

    // ---- the box against the tables -------------------------------------------------------------------------------------------

    private static void OpenTheBox(DialogueAsset asset, string node = "Start")
    {
        Director.AttachToWorld(new DialogueService(), new AlundraGameState());
        Director.InstallForMapEntry();
        Director.Open(asset, node, controlMode: 1);
    }

    private static void SetTheBinaryWidths() =>
        Director.AdvanceProviderForTests = c => AlundraTextBoxOracle.GlyphWidth(OraclePages.ByteOf(c));

    [Theory]
    [MemberData(nameof(ScenarioNames))]
    public void TheBox_DrawsWhatTheTableSays_AtEveryPass(string name)
    {
        var scenario = Of(name);
        var table = LoadTable(name);
        SetTheBinaryWidths();
        OpenTheBox(scenario.Asset());
        var box = Director.Box;

        Assert.False(box.Drawn);
        Assert.False(table[0].Drawn);
        var endingPasses = 0;
        foreach (var t in table.Skip(1))
        {
            var (held, pressed) = scenario.Pad(t.Pass);
            Director.Pass(held, pressed);
            var where = $"{name} pass {t.Pass}";
            Assert.True(t.Drawn == box.Drawn, $"{where}: drawn {box.Drawn}, table {t.Drawn}");
            if (!t.Drawn)
            {
                continue;
            }

            Assert.True(t.FrameY == box.Y, $"{where}: Y {box.Y}, table {t.FrameY}");
            Assert.True((t.ClipTop, t.ClipH) == (box.ClipTop, box.ClipHeight), $"{where}: clip ({box.ClipTop}, {box.ClipHeight}), table ({t.ClipTop}, {t.ClipH})");

            // The one rule for the pass that ends a scroll: the binary draws the old rows 1 and 2 (the ClearImage of the old top band runs before the ordering table is drawn),
            // where the box shows the rows AFTER the shift (D-E19-83): (row 1 of the table, row 2 of the table, empty), at the rows' own y, x 32, offset 0.
            (string Text, int X, int Y)[] expected;
            int expectedOffset;
            if (t.Ending)
            {
                endingPasses++;
                expected = new[]
                {
                    (t.Rows[1].Text, 32, t.FrameY + 5), (t.Rows[2].Text, 32, t.FrameY + 5 + 16), (string.Empty, 32, t.FrameY + 5 + 32),
                };
                expectedOffset = 0;
            }
            else
            {
                expected = t.Rows;
                expectedOffset = t.Offset;
            }

            Assert.True(expectedOffset == box.RowOffset, $"{where}: offset {box.RowOffset}, expected {expectedOffset}");
            for (var r = 0; r < 3; r++)
            {
                var actual = (Shown(box.Row(r)), box.RowX(r), box.Y + 5 + 16 * r - box.RowOffset);
                Assert.True(expected[r] == actual, $"{where}: row {r} {actual}, expected {expected[r]}");
            }

            Assert.True((t.CursorImage ?? -1) == box.CursorImage, $"{where}: cursor image {box.CursorImage}, table {t.CursorImage}");
        }

        Assert.Equal(name == "S4" ? 1 : 0, endingPasses);
    }

    [Fact]
    public void TheBox_WithTheVariantOfTheConstant_DrawsTheRowsBeforeTheShiftOnTheEndingPass()
    {
        SetTheBinaryWidths();
        OpenTheBox(Of("S4").Asset());
        var box = Director.Box;
        Assert.False(AlundraDialogueBox.ScrollEndDrawsPreShiftRows);
        box.DrawsPreShiftRowsAtScrollEnd = true;
        try
        {
            for (var pass = 1; pass <= 100; pass++)
            {
                Director.Pass(false, false);
            }

            Assert.True(box.Drawn);
            Assert.Equal(16, box.RowOffset);
            var rows = Enumerable.Range(0, 3).Select(r => (box.Row(r), box.RowX(r), box.Y + 5 + 16 * r - box.RowOffset)).ToArray();
            Assert.Equal(new[] { ("gypjq", 32, 157), ("deux", 32, 173), ("trois", 32, 189) }, rows);

            Director.Pass(false, false); // pass 101: the next pass shows the shifted rows at offset 0 either way
            Assert.Equal(0, box.RowOffset);
            Assert.Equal(("deux", "trois", string.Empty), (box.Row(0), box.Row(1), box.Row(2)));
        }
        finally
        {
            box.DrawsPreShiftRowsAtScrollEnd = AlundraDialogueBox.ScrollEndDrawsPreShiftRows;
        }
    }

    // ---- the production reader of the advances ---------------------------------------------------------------------------------

    private static DialogueAsset LoadMapAsset(string root, int mapId)
    {
        var file = Directory.GetFiles(Path.Combine(root, "Maps"), $"*-{mapId}.dialogue", SearchOption.AllDirectories)
            .Single(p => Path.GetFileNameWithoutExtension(p).EndsWith("-" + mapId, StringComparison.Ordinal));
        return DialogueTestAssets.LoadFromDisk(file);
    }

    private static void TypeThePage(int maxPasses = 800)
    {
        for (var pass = 0; pass < maxPasses && !Director.Box.IsTypingDone; pass++)
        {
            Director.Pass(false, false);
        }

        Assert.True(Director.Box.IsTypingDone);
    }

    [Fact]
    public void TheRealCentredLineOfThePub_S025OfMap472_IsCentredByTheProductionReaderOfFont3()
    {
        var root = SaveGameDirectorTestSupport.FindProjectRoot();
        EngineEnvironment.ProjectPath = root;
        AlundraFont3Advances.ResetForTests();

        OpenTheBox(LoadMapAsset(root, 472), "M472_S025");
        TypeThePage();
        var box = Director.Box;

        // 43 glyph steps (the 8 trailing spaces of the second line are typed, as in the binary: f2b1a), the widths of the binary (111 and 125 px) and their x.
        Assert.Equal(43, box.GlyphCount);
        Assert.Equal((111, 125), (box.RowWidth(0), box.RowWidth(1)));
        Assert.Equal((104, 97), (box.RowX(0), box.RowX(1)));
        Assert.Equal(32, box.RowX(2));
        Assert.Equal("Roue de la fortune !", box.Row(0));
        Assert.Equal("Florin" + (char)21 + "Roulette        ", box.Row(1));
    }

    [Fact]
    public void AProjectWithoutFont3_GivesWidthZeroAndX32_AndOneWarningPerProjectPath()
    {
        var empty = Path.Combine(Path.GetTempPath(), "alundra-no-font3-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(empty);
        using var logger = new WarningCapture();
        try
        {
            EngineEnvironment.ProjectPath = empty;
            AlundraFont3Advances.ResetForTests();

            OpenTheBox(Of("S3").Asset());
            TypeThePage();
            var box = Director.Box;
            Assert.Equal((0, 0), (box.RowWidth(0), box.RowWidth(1)));
            Assert.Equal((32, 32), (box.RowX(0), box.RowX(1)));
            Assert.Equal("Roue de la fortune !", box.Row(0));

            // Two centred lines, one box: the table is read once for the project path.
            var warnings = logger.Warnings.Where(w => w.Contains("font3.fnt", StringComparison.Ordinal)).ToList();
            Assert.True(warnings.Count == 1, $"{warnings.Count} warnings: {string.Join(" | ", warnings)}");
            Assert.Contains(empty, warnings[0], StringComparison.Ordinal);
        }
        finally
        {
            Directory.Delete(empty, recursive: true);
        }
    }

    private sealed class WarningCapture : ILogger, IDisposable
    {
        private readonly object _gate = new();
        private readonly List<string> _warnings = new();

        public WarningCapture()
        {
            Logs.AddLogger(this);
        }

        public List<string> Warnings
        {
            get
            {
                lock (_gate)
                {
                    return _warnings.ToList();
                }
            }
        }

        public void Close() { }
        public void WriteTrace(string msg) { }
        public void WriteDebug(string msg) { }
        public void WriteInfo(string msg) { }
        public void WriteError(string msg) { }

        public void WriteWarning(string msg)
        {
            lock (_gate)
            {
                _warnings.Add(msg);
            }
        }

        public void Dispose()
        {
            var field = typeof(Logs).GetField("_loggers", BindingFlags.Static | BindingFlags.NonPublic);
            Assert.NotNull(field);
            ((List<ILogger>)field!.GetValue(null)!).Remove(this);
        }
    }
}
