"""gen_rows.py - the unit-test rows of the 0x22 / 0x23 handlers in the DLL frame (PosZ_dll = PosZ_b - 1), generated by running the REAL
handlers of ALUN_CD.EXE with PosZ_b = PosZ_dll + 1.  Every row: (height, PosZ_dll, ForceZ_in, contact) -> (result, ForceZ_out, memo_dll)
where memo_dll = memo_b - 1.  The literal fallback rows (a controller above 256 px) are computed from the rule itself (no binary handler: it is the
documented deviation)."""
import sys, os
sys.stdout.reconfigure(encoding="utf-8")
SP = r"<scratchpad>"
sys.path.insert(0, os.path.join(SP, "f3-disc", "binary"))
import emu as E

ENT, REC, ST, PCV, CODE = 0x80100000, 0x80101000, 0x80102000, 0x80103000, 0x80104000


def make():
    m = E.Emu()
    m.hooks[0x8003C840] = lambda mm: None
    return m


def run(addr, height, seq):
    m = make()
    for i in range(0x400):
        m.wb(ENT + i, 0)
    for i in range(0x40):
        m.wb(ST + i, 0)
    m.wb(CODE, 0x22 if addr == 0x8003DA70 else 0x23)
    m.ww(PCV, CODE)
    m.ww(ENT + 0x44, REC)
    for i in range(0x20):
        m.wb(REC + i, 0)
    m.wb(REC + 9, height)
    out = []
    for (posz_dll, forcez, contact) in seq:
        m.ww(ENT + 0x11C, (posz_dll + 1) & 0xFFFFFFFF)       # the binary frame
        m.ww(ENT + 0xB8, forcez & 0xFFFFFFFF)
        m.ww(ENT + 0x140, contact)
        r = E.s32(m.call(addr, ENT, ENT, PCV, ST))
        out.append((posz_dll, forcez, contact, r, m.rws(ENT + 0xB8), m.rws(ST + 0xC) - 1))
    return out


def show(title, rows):
    print("==", title)
    for posz, f, c, r, fo, memo in rows:
        print("  PosZ %9d ForceZ %9d contact %d -> result %d  ForceZ out %9d  memo(DLL frame) %d" % (posz, f, c, r, fo, memo))


# 0x22, Height 20 (literal 10485760): the rows of the current test, shifted by -1 on PosZ
seq20 = [(10484999, 0, 0), (10484999, 32768, 0), (10484999, 700, 0), (10485759, 0, 0), (10485760, -5, 0), (10485760, 0, 0),
         (9999999, -32768, 0), (9999999, 600000, 0), (10485759, 32768, 1),
         # new rows around the descent shape (binary: PosZ_b = target + 1 -> a -1 step)
         (10485760, -32768, 0), (10485760 + 32768, -32768, 0), (10485760 + 5, -32768, 0)]
# first call (memo) needs a dummy first row: the handler memorises at the first call whatever the state
show("0x22 Height 20: literal 10485760 -> DLL target 10485759", run(0x8003DA70, 20, [(10485000, 0, 0)] + seq20)[1:])
# 0x23 Height 30
seq30 = [(15000000, 0, 0), (15000000, 32768, 0), (15000000, 32768, 1), (15728639, 0, 0)]
show("0x23 Height 30: literal 15728640 -> DLL target 15728639", run(0x8003DB28, 30, [(15000000, 0, 0)] + seq30)[1:])
# Height 38 (304 px): shifted target 19922943 for an entity WITHOUT a controller
show("0x22 Height 38 (no controller): DLL target 19922943", run(0x8003DA70, 38, [(19922000, 0, 0), (19890175, 32768, 0), (19922943, 0, 0), (19922944, -5, 0)])[1:])
# the memo (first call) rows
for h in (6, 10, 12, 14, 20, 22, 30, 32, 33, 38):
    lit = h << 19
    print("Height %2d: literal %9d (%6.1f px)  DLL shifted target %9d  controller target %9d" % (h, lit, lit / 65536, lit - 1, (lit if lit - 1 >= (1 << 24) else lit - 1)))

# the literal fallback rows (controller, Height 38): computed by the rule, handler algebra on the literal target
def lit_rows(height, seq):
    t = height << 19
    rows = []
    for posz, f, c in seq:
        if posz == t:
            rows.append((posz, f, c, 1, f, t)); continue
        d = t - posz
        fo = f
        if d > 0:
            if d < f: fo = d
        else:
            if f < d: fo = d
        rows.append((posz, f, c, 0, fo, t))
    return rows
show("0x22 Height 38, CONTROLLER (literal target 19922944, deviation above 256 px)", lit_rows(38, [(19890176, 32768, 0), (19922944, 32768, 0), (19922943, 32768, 0), (19921000, 32768, 0)]))
